language: java

jdk:
  - oraclejdk7

env:
  matrix:
    - PATH=$PATH:/tmp/sonar-scanner-2.5/bin SONAR_DL=https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-4.5.6.zip SONAR_HOME=/tmp/sonarqube-4.5.6 RAILS_ENV=production
    - PATH=$PATH:/tmp/sonar-scanner-2.5/bin SONAR_DL=http://downloads.sonarsource.com/sonarqube/sonarqube-5.0.1.zip SONAR_HOME=/tmp/sonarqube-5.0.1 RAILS_ENV=production
    - PATH=$PATH:/tmp/sonar-scanner-2.5/bin SONAR_DL=https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-5.1.2.zip SONAR_HOME=/tmp/sonarqube-5.1.2 RAILS_ENV=production
    - PATH=$PATH:/tmp/sonar-scanner-2.5/bin SONAR_DL=https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-5.2.zip SONAR_HOME=/tmp/sonarqube-5.2 RAILS_ENV=production
    - PATH=$PATH:/tmp/sonar-scanner-2.5/bin SONAR_DL=https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-5.3.zip SONAR_HOME=/tmp/sonarqube-5.3 RAILS_ENV=production
    - PATH=$PATH:/tmp/sonar-scanner-2.5/bin SONAR_DL=https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-5.4.zip SONAR_HOME=/tmp/sonarqube-5.4 RAILS_ENV=production
    - PATH=$PATH:/tmp/sonar-scanner-2.5/bin SONAR_DL=https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-5.5.zip SONAR_HOME=/tmp/sonarqube-5.5 RAILS_ENV=production
    - PATH=$PATH:/tmp/sonar-scanner-2.5/bin SONAR_DL=https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-5.6.2.zip SONAR_HOME=/tmp/sonarqube-5.6.2 RAILS_ENV=production
    - PATH=$PATH:/tmp/sonar-scanner-2.5/bin SONAR_DL=https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-6.0.zip SONAR_HOME=/tmp/sonarqube-6.0 RAILS_ENV=production

install:
  - cd /tmp
  - wget -O sonarqube.zip $SONAR_DL
  - unzip sonarqube.zip
  - wget https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-2.5.zip
  - unzip sonar-scanner-2.5.zip
  - ls -lar
  - cd -
  - sudo gem install puppet -v 3.8.6

script:
  - ./gradlew build localDeploy functionalTest -Psonar.pluginDir=$SONAR_HOME/extensions/plugins

before_install:
 - chmod +x gradlew

after_success:
 - ./gradlew jacocoTestReport coveralls
