sudo: required

language: java

services: docker

jdk: oraclejdk8

env:
  matrix:
    - SONARQUBE_VERSION=5.6.6 PATH=/tmp/sonar-scanner-2.5/bin:$PATH
    - SONARQUBE_VERSION=6.0 PATH=/tmp/sonar-scanner-2.5/bin:$PATH
    - SONARQUBE_VERSION=6.1 PATH=/tmp/sonar-scanner-2.5/bin:$PATH
    - SONARQUBE_VERSION=6.2 PATH=/tmp/sonar-scanner-2.5/bin:$PATH
    - SONARQUBE_VERSION=6.3 PATH=/tmp/sonar-scanner-2.5/bin:$PATH

install:
  - echo "FROM sonarqube:${SONARQUBE_VERSION}-alpine" > Dockerfile.ci
  - echo "COPY sonar-puppet-plugin/build/libs/* /opt/sonarqube/extensions/plugins/" >> Dockerfile.ci
  - docker build -t sonar-puppet -f Dockerfile.ci .
  - docker run -d --name sonarqube -p 9000:9000 -p 9092:9092 sonar-puppet
  - cd /tmp
  - wget https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-2.5.zip
  - unzip sonar-scanner-2.5.zip
  - cd -
  - gem install puppet -v 3.8.6

script:
  - ./gradlew build functionalTest

before_install:
 - chmod +x gradlew

after_success:
 - ./gradlew jacocoTestReport coveralls
